name: prod
on: workflow_call

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: 🔨 Build Project
        run: |
          pnpm install
          pnpm build

      - name: ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist
          server-dir: temp
