name: prod
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: 🔨 Build Project
        run: |
          pnpm install
          pnpm build

      # Docker wrapper for `lftp` https://lftp.yar.ru/lftp-man.html
      - name: ftp
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.FTP_SERVER}}
          user: ${{ secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./dist/
          remoteDir: ./httpdocs/
